[package]
name = "zenith"
version = "0.3.0"
authors = ["Benjamin Vaisvil <benjamini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.6.1"
termion = "1.5"
ctrlc = "3.1.3"
rand = "0.7.0"
byte-unit = "3.0.3"
maplit = "1.0.2"
users = "0.9.1"
sys-info = "0.5.8"
num = "0.2.0"
num-derive = "0.3.0"
num-traits = "0.2"
heim = "^0.0.8"
futures = "0.3.1"
[dependencies.sysinfo]
path = "../sysinfo"