[package]
name = "zenith"
version = "0.7.5"
authors = ["Benjamin Vaisvil"]
edition = "2018"
description = "Similar to top or htop but with CPU, Network Usage, and Disk Usage charts."
readme = "README.md"
homepage = "https://github.com/bvaisvil/zenith"
repository = "https://github.com/bvaisvil/zenith"
license = "MIT"
keywords = ["system monitor", "tui", "process monitor", "sysinfo"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.6.*"
termion = "1.5"
byte-unit = "3.0.3"
users = "0.9.1"
sys-info = "0.5.8"
num = "0.2.0"
num-derive = "0.3.0"
num-traits = "0.2"
heim = "0.0.9"
futures = "0.3.1"
clap = "2.31.*"
chrono = "0.4.*"
sysinfo = {git = "https://github.com/bvaisvil/sysinfo", branch="zenith_changes"}
sled = "0.31.*"
dirs = "2.0.*"
serde = {version="1.0.104", features=["derive"]}
serde_derive = "1.0.104"
bincode = "1.2.1"
#sysinfo = {path = "../sysinfo"}
