[package]
name = "zenith"
version = "0.7.2"
authors = ["Benjamin Vaisvil"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.6.2"
termion = "1.5"
byte-unit = "3.0.3"
users = "0.9.1"
sys-info = "0.5.8"
num = "0.2.0"
num-derive = "0.3.0"
num-traits = "0.2"
heim = "0.0.9"
futures = "0.3.1"
clap = "2.31.*"
chrono = "0.4.*"
sysinfo = {git = "https://github.com/bvaisvil/sysinfo", branch="zenith_changes"}
#sysinfo = {path = "../sysinfo"}
